### ISSUE TITLE
请问如何从checkpoints中继续训练呢

### ISSUE THREAD

**Issue by RJshra** [myweihp/Jittor-MeAndMyCuteUncles-LandscapeTrack#1]
感谢你们的工作！
但我在训练的时候遇到了问题，不知道如何从checkpoints中读取数据继续训练

**Comment by myweihp** [comment]
您好，
您可以在运行命令后添加"--continue_train"选项，会根据默认的check point保存位置（./checkpoints）读取之前的参数；如果需要另外指定模型位置，可以参考”--checkpoints_dir“选项。
上述相关命令行选项您可以在options/train_options和options/base_options找到。

**Comment by RJshra** [comment]
十分感谢，我在阅读了options的参数后找到了答案
